# Not used by yaml
$schema: "./config.schema.json"

# AppStack default configuration
$imports: "@azera/stack/default.config.yml"

# Config resolver options
config:
    allowExtra: false

# Container parameters
parameters:
    httpPort: 8090
    twigCache: true

# Http bundle configuration
web:
    forks: 1
    port: 8090
    routes:
        /function: /Controller/FunctionController
        /testLogin: /Controller/LoginController::loginAction
        /public:
            resource: ./public
            type: static

# Services
services:
    - /Command/RunCommand
    - /Command/DumpParametersCommand
    - /Controller/IndexController
    - /Command/TestCommand

# Kernel
kernel:
    cacheDir: ./cache
    cacheConfig: false
    handleError: false

# Database connections
typeOrm:
    defaultConnection: cmis
    connections:
        main:
            type: mongodb
            host: localhost
            port: 27017
            useNewUrlParser: true
            useUnifiedTopology: true
            database: test
        cmis:
            type: mssql
            database: ODCC_NEW
            username: mdzzohrabi
            password: md#1372#
            host: localhost
            entities:
                - /entity/Project
                - /entity/Config

# Models
models:
    UserA:
        dataSource: main
        collection: users
        fields:
            - name: username
              type: string
            - name: age
              type: number
    Project:
        dataSource: cmis
        collection: CM.Project
        fields:
            - name: Id
              type: int
              primary: true
            - name: Name
              type: varchar

# Graph bundle configuration
graph:
    port: 2222

# Asset bundle
assets:
    # Storages
    storages:
        - name: local
          provider: local
          path: "./public"
          description: Local Storage
        
# Web-client configuration
web_client:
    proxy: http://172.16.8.12:39741

# Cache
cache:
    # Providers
    providers:
        temp:
            type: file
            path: "./cache"
        memory:
            type: memory
    defaultProvider: memory

message:
    transports:
        crawler:
            transport: amqp://localhost/crawl
            types:
                - /message/CrawlMessage

# Workflows
workflow:
    workflows:
        blog_post:
            places:
                - saved
                - posted
                - accepted
            transitions:
                post: { from: saved, to: posted }
                accept: { from: posted, to: accepted }
            initial: saved
            property: status
            supports: /model/Post

event_manager:
    events:
        workflow.transition:
            - /events/WorkflowListener::beforeTransition

mongoose:
    defaultConnection: main
    #proxy: http://172.16.8.12:39741
    connections:
        main:
            #uri: mongodb://171.22.27.137:27017/expo
            #user: expo
            #pass: expo#mdzzohrabi#1372#
            dbName: expo
            useNewUrlParser: true
            useUnifiedTopology: false
            models:
                - /model/MongoBook