# $schema: ./config.schema.json
$imports:
    - '@azera/stack/config.yml'

config: { allowExtra: true }

customConfig: Yes

parameters:
    httpPort: 8090
    # httpViews: ./views

# Routes collection
routes:
    $imports: ./config/routes.yml

services:
    /Command/RunCommand: ~
    /Command/DumpParametersCommand: ~
    /Command/GetTaggedServicesCommand: ~
    /Controller/IndexController: ~

kernel:

    # Cache kernel resolved config
    cacheConfig: false